// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practicaweb.API.DBContexts;

#nullable disable

namespace Practicaweb.API.Migrations
{
    [DbContext(typeof(InfoUsersContext))]
    partial class InfoUsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Practicaweb.API.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CUIT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CUIT = 1254769865L,
                            Description = "15 fusiles AR15",
                            Name = "Nick Gaturro Cotillon",
                            Price = 15885.200000000001,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CUIT = 6986556654L,
                            Description = "4 peras",
                            Name = "COTO",
                            Price = 52000.550000000003,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CUIT = 1125446852L,
                            Description = "20 Ficus con maceta",
                            Name = "Easy",
                            Price = 41000.330000000002,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Practicaweb.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User 3"
                        });
                });

            modelBuilder.Entity("Practicaweb.API.Entities.Bill", b =>
                {
                    b.HasOne("Practicaweb.API.Entities.User", "user")
                        .WithMany("Bill")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Practicaweb.API.Entities.User", b =>
                {
                    b.Navigation("Bill");
                });
#pragma warning restore 612, 618
        }
    }
}
